server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      routes:
        - id: USER-SERVICE
          uri: lb://TIMEKEEPLOGIN
          predicates:
            - Path=/apiV1/**
        - id: DEPARTMENT-SERVICE
          uri: lb://TIMEKEEPV1
          predicates:
            - Path=/api/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost